Uhf 8103 sitemap urls
City-of-Helsinki/drupal-module-helfi-proxy pull request #52
Opened 2023-02-23 07:28 UTC by rpnykanen

# [UHF-8103](https://helsinkisolutionoffice.atlassian.net/browse/UHF-8103)
enhance simple sitemap url generation in certain cases

## What was done
Dynamically set simple_sitemap baseurl config override if module is installed.

## How to install

* Make sure your instance is up and running on correct branch.
* run `composer require drupal/helfi_proxy:dev-UHF-8103_sitemap_urls`
* run `drush cr`

## How to test

* reload any page after cache clear
* run inside container `drush php:eval "echo json_encode(\Drupal::service('config.factory')->get('simple_sitemap.settings')->get('base_url'));"`
* the command should print "{project.docker.so}/{langcode}/{site-prefix}"

2023-02-23 09:08 UTC, juho-lehmonen requested changes
This caused duplicates at least in the Rekry instance:
```
<url>
  <loc>https://helfi-rekry.docker.so/fi/avoimet-tyopaikat/fi/avoimet-tyopaikat</loc>
  <xhtml:link rel="alternate" hreflang="fi" href="[https://helfi-rekry.docker.so/fi/avoimet-tyopaikat/fi/avoimet-tyopaikat](view-source:https://helfi-rekry.docker.so/fi/avoimet-tyopaikat/fi/avoimet-tyopaikat)"/>
  <xhtml:link rel="alternate" hreflang="sv" href="[https://helfi-rekry.docker.so/fi/avoimet-tyopaikat/sv/lediga-jobb](view-source:https://helfi-rekry.docker.so/fi/avoimet-tyopaikat/sv/lediga-jobb)"/>
  <xhtml:link rel="alternate" hreflang="en" href="[https://helfi-rekry.docker.so/fi/avoimet-tyopaikat/en/open-jobs](view-source:https://helfi-rekry.docker.so/fi/avoimet-tyopaikat/en/open-jobs)"/>
  <lastmod>2023-01-11T13:35:31+02:00</lastmod>
  <changefreq>daily</changefreq>
  <priority>1.0</priority>
 </url>
<url>
  <loc>https://helfi-rekry.docker.so/fi/avoimet-tyopaikat/en/open-jobs/open-jobs/palke-02-5-23</loc>
  <xhtml:link rel="alternate" hreflang="fi" href="[https://helfi-rekry.docker.so/fi/avoimet-tyopaikat/fi/avoimet-tyopaikat/avoimet-tyopaikat/palke-02-5-23](view-source:https://helfi-rekry.docker.so/fi/avoimet-tyopaikat/fi/avoimet-tyopaikat/avoimet-tyopaikat/palke-02-5-23)"/>
  <xhtml:link rel="alternate" hreflang="sv" href="[https://helfi-rekry.docker.so/fi/avoimet-tyopaikat/sv/lediga-jobb/lediga-jobb/palke-02-5-23](view-source:https://helfi-rekry.docker.so/fi/avoimet-tyopaikat/sv/lediga-jobb/lediga-jobb/palke-02-5-23)"/>
  <xhtml:link rel="alternate" hreflang="en" href="[https://helfi-rekry.docker.so/fi/avoimet-tyopaikat/en/open-jobs/open-jobs/palke-02-5-23](view-source:https://helfi-rekry.docker.so/fi/avoimet-tyopaikat/en/open-jobs/open-jobs/palke-02-5-23)"/>
  <lastmod>2023-02-13T08:51:42+02:00</lastmod>
  <priority>0.5</priority>
 </url>
```

Also happens on the SOTE instance:
```
<url>
  <loc>https://helfi-sote.docker.so/en/health-and-social-services/fi/sosiaali-ja-terveyspalvelut/terveydenhoito/terveysasemat</loc>
  <xhtml:link rel="alternate" hreflang="fi" href="[https://helfi-sote.docker.so/en/health-and-social-services/fi/sosiaali-ja-terveyspalvelut/terveydenhoito/terveysasemat](view-source:https://helfi-sote.docker.so/en/health-and-social-services/fi/sosiaali-ja-terveyspalvelut/terveydenhoito/terveysasemat)"/>
  <xhtml:link rel="alternate" hreflang="sv" href="[https://helfi-sote.docker.so/en/health-and-social-services/sv/social-och-halsovardstjanster/halsovard/halsostationer](view-source:https://helfi-sote.docker.so/en/health-and-social-services/sv/social-och-halsovardstjanster/halsovard/halsostationer)"/>
  <xhtml:link rel="alternate" hreflang="en" href="[https://helfi-sote.docker.so/en/health-and-social-services/en/health-and-social-services/health-care/health-stations](view-source:https://helfi-sote.docker.so/en/health-and-social-services/en/health-and-social-services/health-care/health-stations)"/>
  <lastmod>2022-12-21T09:44:00+02:00</lastmod>
  <priority>0.5</priority>
 </url>
```

2023-02-27 07:14 UTC, khalima reviewed
_This comment has been deleted_

2023-02-27 07:16 UTC, khalima commented on helfi_proxy.module
> +    foreach ($alternateUrls as $key => &$alternateUrl) {
Here's a duplicated `$key` variable.

2023-02-28 07:10 UTC, juho-lehmonen approved these changes

2023-02-28 07:10 UTC, merged